dist: trusty
sudo: required
language: csharp
mono: none
dotnet: 2.1.101
before_install:
  - docker run -d -p 6379:6379 redislabs/redisearch:latest --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
script:
  - dotnet clean -c Release -o ./dist
  - dotnet build ./RediSearchSharp.sln -c Release -o ./dist
  - dotnet test -c Release --no-build --no-restore ./RediSearchSharp.Test/RediSearchSharp.Test.csproj -o ./dist -r "$TEST_RESULTS_PATH"