dist: trusty
sudo: required
language: csharp
mono: none
dotnet: 2.1.4
before_install:
  - docker run -d -p 6379:6379 redislabs/redisearch:latest --protected-mode no --loadmodule /usr/lib/redis/modules/redisearch.so
before_script:
  - source scripts/install-sonarcloud.sh
  - chmod +x scripts/build.sh
  - chmod +x scripts/test.sh
script:
  - echo $PATH
  - dotnet "$HOME/.sonarscanner/SonarScanner.MSBuild.dll" begin /k:"ojji.redisearchsharp" /d:sonar.organization="ojji-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_TOKEN" /d:sonar.cs.vstest.reportsPaths="$TEST_RESULTS_PATH/*.trx"
  - ./scripts/build.sh
  - ./scripts/test.sh
  - dotnet "$HOME/.sonarscanner/SonarScanner.MSBuild.dll" end /d:sonar.login="$SONAR_TOKEN"